### PR TITLE
cf-ssh script automates local setup/cleanup of ssh

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Thanks @jbayer for introducing me to tmate-bootstrap today!

**Comment by drnic** [comment]
Here's a youtube demo of the `cf-ssh` command http://www.youtube.com/watch?v=eWJCfAa1_x8&feature=youtu.be

I'll publish a blog post if/when you merge the PR.

**Comment by drnic** [comment]
Blog post https://blog.starkandwayne.com/2014/07/14/running-one-time-tasks-in-cloud-foundry/

Notable limitations (documented in blog post)
- does not know if target application used a custom buildpack
- does not know if target application created with a target file (jar) rather than source project
- does not look for a manifest.yml either

**Comment by drnic** [comment]
@danhigham  ^^

**Comment by drnic** [comment]
@jambay thought: creating an ssh/tmate version of a running application would be faster and more deterministic if there was a way to create an app based on an existing droplet

**Comment by drnic** [comment]
Latest commits add buildpack & path support.

**Comment by danhigham** [comment]
Thanks Nic, I had plans to add your script!

**Pull request merged**
